---
- name: Delete VM "{{ proxmox_guest_hostname }}/{{ proxmox_vm_state }}"
  community.general.proxmox_kvm:
    proxmox_default_behavior: "no_defaults"
    node: "{{ proxmox_pve_node }}"
    api_user: "{{ proxmox_pve_user }}"
    api_password: "{{ proxmox_pve_password }}"
    api_host: "{{ proxmox_pve_api_node }}"
    name: "{{ proxmox_guest_hostname }}"
    state: "absent"
